name: Build and Deploy to Yandex cloud

on:
  push:
    branches:
      - main

jobs:
  setup-build-publish-deploy:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Set up Maven
        uses: stCarolas/setup-maven@v4.2
        with:
          maven-version: 3.8.2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Build docker image with Maven
        run: mvn spring-boot:build-image
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.CR_YANDEX_REPO }}
          username: oauth
          password: ${{ secrets.OAUTH_TOKEN }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VM_IP }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            sudo docker stop pro-bot
            docker run pro-bot